repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      # TODO: Uncomment when we are ready to fix the linting
      # - id: ruff-check
      #   args: [--fix] # TODO: Do we want this?
      # Run the formatter.
      - id: ruff-format
